lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'java.lang:type=GarbageCollector,name=.*'
    name: jvm_gc_collection_seconds_count
    labels:
      gc: $1
  - pattern: 'java.lang:type=Threading'
    name: jvm_threads_started_total
