lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: 'java.lang<type=Runtime, key=java.runtime.name><>SystemProperties: (.*)'
    name: jvm_runtime
    value: 1
    labels:
      runtime: "$1"